# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]
    
jobs:

  build-web-test:
    runs-on: ubuntu-latest
    steps:
#       - name: checkout
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false # Per the GitHub Pages action below
      - name: VueCap web
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: c5c9fcb5
          platform: Web
          artifact-retention-days: 1
