# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]
    
jobs:
  # This will build an IPA & Upload the artifact in iOS.zip

  build-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
          repository: 'likhithIonic/dev'        
    # 
  build-web-test:
    runs-on: ubuntu-latest
    steps:
      - name: VueCap web
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: a9bdd75c
          platform: Web
          artifact-retention-days: 1
